name: test worker

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
    test_worker:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
        
            - name: set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
    
            - name: deploy flows
              run: prefect --no-prompt deploy
    
            - name: start worker
              run: prefect worker start -p local


